---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zouwenhao.
--- DateTime: 2022/5/31 11:38 上午
---

--local socket = require("socket.core")
local roundrobin = require("loadbalance.roundrobin")
local smoothroundrobin = require("loadbalance.smoothroundrobin")
local json = require("util.json")

--local mobdebug = require("add.initial.mobdebug");
--mobdebug.start();

--a = 1
--print("hha")
local args = ngx.req.get_uri_args()
local nodeSize = args["node_size"]
local qps = tonumber(args["qps"])
local time = args["time"]

local nodes={}
-- 5个节点
--for i = 1, 5 do
for i = 1, nodeSize do
    local str = "N" .. i
    nodes[str] = 100 -- 权重100
end

local function request(nodes, type, s, lowNode)
    local counts = {}
    local picker1
    local count = 0
    local showFirst = false
    local lowSize = 0
    if type == "wrr" then
        picker1 = roundrobin:new(nodes)
    else if type == "swrr" then
        picker1 = smoothroundrobin:new(nodes)
    end
    end
    -- 模拟请求，发现s次
    for i = 1, s do
        local pick = picker1:find()
        --ngx.log(ngx.ERR, "find:" .. pick)
        if counts[pick] == nil then
            counts[pick] = 1
        else
            counts[pick] = counts[pick] + 1
        end
        count = count + 1
        if pick == lowNode then
            lowSize = lowSize + 1
            if lowSize == 2 then
                ngx.log(ngx.ERR, "lownode:" .. lowNode .. " lowcount:" .. count .. " lowSize:" .. lowSize)
                return count
            end
            showFirst = true
            ngx.log(ngx.ERR, "lownode:" .. lowNode .. " first count:" .. count)
        end

    end
    ngx.log(ngx.ERR, "roundrobin result:" .. json.encode(counts) .. " type:" .. type)

    -- 判断请求占比是否接近权重
    if false then
        local node = "N1"
        local tw = 0
        for _, n in pairs(nodes) do
            tw = n + tw
        end
        local ratio = nodes[node] / tw
        local target = ratio * s
        local count = 0
        if counts[node] ~= nil then
            count = counts[node]
        end
        ngx.log(ngx.ERR, "count:" .. count .. " target:" .. target)
        --assert(count + 1 >= target and count - 1 < target +1) -- wrr会低权重时会失败 ，权重3+5节点300请求时
        --if type == "swrr" then
        --    assert(count + 1 >= target and count - 1 < target +1)
        --end
    end
end

-- 请求（预热）
local start_time = os.time()
local lastCount = 0
local requestCount = qps * time / 192
ngx.log(ngx.ERR, "requestCount:" .. requestCount)
for i = 1, 100 do
    local lowNode = "N1"
    nodes[lowNode] = i
    ngx.log(ngx.ERR, "---weight up:" .. i .. "---")
    local s = qps
    s = s*time -- 请求总数
    ngx.log(ngx.ERR, "request size:" .. s)
    --request(nodes, "wrr", s)
    local count = request(nodes, "swrr", s, lowNode)
    if count < requestCount then
        if lastCount - requestCount < requestCount - count then
            ngx.print(i-1)
            return
        end
        ngx.print(i)
        return
    end
    lastCount = count
    --ngx.exit(0)
end
local end_time = os.time()
ngx.log(ngx.ERR, "---done:--- start_time:" .. start_time .. " end:" .. end_time)


--local picker1 = roundrobin:new(nodes)
--local pick = picker1:find()
--ngx.log(ngx.ERR, pick)

assert(true)